[package]
name = "rag"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-extract = "0.9.0"
reqwest = { version = "0.12.22", features = ["blocking"] }
serde_json = "1.0.142"
text-splitter = "0.27.0"
tinyvector = "0.0.1"
